### ISSUE TITLE
PSVR: StreamView rendered weird for close objects

### ISSUE THREAD

**Issue by mungewell** [RiftCat/vridge-api#18]
Not sure whether you want bug like this reported here, or somewhere else.

In the Construct (empty dome in SteamVR) if I place the viewport close to the floor (0,-0.4,0) the lines crossing the point under my feet render weird. In the headset they appear as a cross, with my eyes each seeing their/single line.

Any suggestions as to what's wrong, and what to change in the 'vridge.cfg' to correct?

![clode_lines_crossed_in_headset](https://user-images.githubusercontent.com/236907/48598240-da61be00-e959-11e8-8aa6-5fd3952df348.png)

**Comment by balukin** [comment]
Generally when you look at something very close to your eyes, you will see two objects as your eyes can't focus on it easily. If you hold a finger close to your eyes, between them - each eye will see opposite side of the finger, resulting in brain not being able to process it into single image. 

Looking at one infinite line, beginning close to your eyes, will effectively result in the same line going at opposite directions for each eye with brain composing it into "a cross". 

In real life this can be adjusted by rotating your eyes (https://en.wikipedia.org/wiki/Vergence). In VR convergence point is at fixed distance which makes it hard to perceive objects which are very close.  Games usually avoid situations where gamers would need to focus their gaze on an object too close to the camera.

I'm not sure if it's the same thing as you're seeing because it's hard to tell without testing it with exactly same setup & lenses. You can post your vridge.cfg here so we could test it on our side with screen similar to PSVR's.
